name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build
        run: cargo build --verbose
      - name: Build examples
        run: cargo build --example basic && cargo build --example errors && cargo build --example hello
      - name: Run tests
        run: cargo test --verbose
